server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javasy?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 3

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# 设置freemarker
freemarker:
  allow-request-override: false
  # 开发过程建议关闭缓存
  cache: false
  check-template-location: false
  charset: UTF-8
  content-type: text/html; charset=utf-8
  expose-request-attributes: false
  expose-session-attributes: false
  expose-spring-macro-helpers: false
  request-context-attribute:
  # 默认后缀就是.ftl
  suffix: .ftl
  template-loader-path: classPath:/templates/